# Generated by Django 5.2.15 on 2026-07-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('blurb', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('system', models.CharField(blank=True, default='', help_text='e.g. MOBILE / AI SYSTEM', max_length=80)),
                ('status', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField()),
                ('stack', models.CharField(blank=True, default='', help_text='Comma-separated, e.g. Flutter, Firebase, OCR', max_length=300)),
                ('accent', models.CharField(default='#8b5cf6', help_text='Hex color', max_length=9)),
                ('url', models.URLField(blank=True, default='')),
                ('featured', models.BooleanField(default=False, help_text='Spans two columns')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ömür Ravlı', max_length=120)),
                ('role', models.CharField(default='Multidisciplinary Engineer & Developer', max_length=160)),
                ('location', models.CharField(default='Kayseri, Türkiye', max_length=120)),
                ('university', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(default='omurravli04@gmail.com', max_length=254)),
                ('github', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('cv_url', models.URLField(blank=True, default='', verbose_name='CV URL')),
                ('hero_badge', models.CharField(default='SYSTEMS ONLINE — KAYSERI, TÜRKİYE', max_length=160)),
                ('hero_heading_lead', models.CharField(default='Ömür Ravlı builds where', max_length=200)),
                ('hero_heading_accent', models.CharField(default='software meets machines', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('color', models.CharField(default='#8b5cf6', help_text='Hex color, e.g. #a78bfa', max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, default='+', max_length=8)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('context', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Timeline entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='content.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
